apiVersion: v1
kind: Service
metadata:
 name: lb-backend-service
 namespace: trainer-portal
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 3000
 selector:
   app: backend-app